// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wjujhddezxqfbeqhjvlm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndqdWpoZGRlenhxZmJlcWhqdmxtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUxMDg0NzUsImV4cCI6MjA1MDY4NDQ3NX0.48uwJRh37-HTI7tUbgaNlZLtFm9yXTJ8H_bozZkiKqc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);